spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.115.255.27:3306/jh_community_light?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: P@ssw0rd123#
    #配置 Jpa
    jpa:
      properties:
        hibernate:
          ddl-auto: none
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: true

    redis:
      #数据库索引
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      #连接超时时间
      timeout: 5000