server:
  port: 8082
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      one: #数据源1
        url: jdbc:mysql://81.68.124.103:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: lilishop
      two: #数据源2
        url: jdbc:mysql://81.68.124.103:3306/test2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: lilishop
    #    url: jdbc:mysql://oa.xmay.cc:33060/xmayAuthority?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: Aa123456
    #配置 Jpa
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true
    open_in_view: false
#    show_sql: true


  redis:
      #配置redis
    database: 1
    host: 81.68.124.103
    port: 6379
    password: lilishop
      #超时时间
    timeout: 5000

rocketmq:
  name-server: 81.68.124.103:9876
  producer:
    group: pj_test_group
#华为云obs
OBS:
  END_POINT: "https://obs.cn-north-1.myhuaweicloud.com"
  BUCKET_NAME: "obs-qych"
  URL: "https://obs-qych.obs.cn-north-1.myhuaweicloud.com/"
  AK: "6HFIA79OWU1DAWBKFEEF"
  SK: "tILhHA7wSEly0cqAL0olPzbk3xojTWNpcnAygVuz"

jwt:
  tokenHeader: PJ-Token #JWT存储的请求头
  tokenHead: Bearer  #令牌前缀
  secret: pangjieAdminSecretpangjieAdminSecretpangjieAdminSecretpangjieAdminSecretpangjieAdminSecretpangjieAdminSecret #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间秒(60*60*24)
