---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pangj.
--- DateTime: 2023/8/8 16:01
---

-- 调用放传递的keys 和 values  execute(RedisScript<T> script, List<K> keys, Object... args)
local keys = KEYS
local values = ARGV;

local function execute()

    local nowLike = redis.call("hget", keys[1], values[1])
    if nowLike == "1" then
        if values[2] == "0" then
            redis.call("incrby", keys[2], "-1")
        end
    else
        redis.call("incrby", keys[2], "1")
    end

    redis.call("hset", keys[1], values[1], values[2])

    return true
end

return execute()